language: python
python:
  - "2.7"
  - "3.6"
script:
    - echo "Building documentation..."
    - pip install -r requirements.txt
    - cd docs
    - make html
    - cd ../
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs/_build/html
  target_branch: gh-pages
  on:
    branch: master
